# Generated by Django 6.0 on 2026-02-13 03:19

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Platform Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='platforms/')),
                ('website', models.URLField()),
                ('country', models.CharField(blank=True, default='Global', max_length=100)),
                ('flag', models.CharField(blank=True, help_text='🇮🇳 🇺🇸 🇬🇧 etc', max_length=10)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all', 'All Levels')], default='beginner', max_length=20)),
                ('description', ckeditor.fields.RichTextField()),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('our_margin', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('student_price_markup', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('affiliate_link', models.URLField(blank=True)),
                ('affiliate_code', models.CharField(blank=True, max_length=100)),
                ('cookie_duration', models.IntegerField(default=30, help_text='Days')),
                ('is_hidden_gem', models.BooleanField(default=False, help_text="💎 90% students don't know")),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('total_products', models.IntegerField(default=0, editable=False)),
                ('total_students', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=4.5, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='platforms.platformcategory')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('preview_video', models.URLField(blank=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('our_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('product_type', models.CharField(choices=[('course', 'Course'), ('subscription', 'Subscription'), ('lab', 'Lab'), ('certification', 'Certification'), ('bundle', 'Bundle')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all', 'All Levels')], default='beginner', max_length=20)),
                ('duration_hours', models.IntegerField(blank=True, null=True)),
                ('has_certificate', models.BooleanField(default=False)),
                ('affiliate_link', models.URLField(blank=True)),
                ('purchase_link', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('students_enrolled', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='platforms.platform')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='platforms.productcategory')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, upload_to='bundles/')),
                ('original_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('bundle_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('savings_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('savings_percentage', models.IntegerField(editable=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(related_name='bundles', to='platforms.product')),
            ],
        ),
    ]
