# Generated by Django 6.0 on 2026-02-13 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('provider', models.CharField(max_length=100)),
                ('provider_logo', models.ImageField(blank=True, upload_to='certifications/')),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('duration_hours', models.IntegerField(blank=True, null=True)),
                ('price_type', models.CharField(choices=[('free', 'Free'), ('free_with_aid', 'Free with Financial Aid'), ('paid', 'Paid')], max_length=20)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('our_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('official_url', models.URLField()),
                ('affiliate_link', models.URLField(blank=True)),
                ('is_hidden_gem', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(help_text='🇮🇳 🇺🇳 etc', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Gem Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('provider', models.CharField(max_length=100)),
                ('provider_logo', models.ImageField(blank=True, upload_to='labs/')),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('lab_count', models.IntegerField(default=1, help_text='Number of labs/challenges')),
                ('is_free', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('our_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('url', models.URLField()),
                ('is_hidden_gem', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='🛣️', max_length=50)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('duration_months', models.IntegerField(default=6)),
                ('total_phases', models.IntegerField(default=0, editable=False)),
                ('total_resources', models.IntegerField(default=0, editable=False)),
                ('hidden_gems_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HiddenGem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('provider', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('flag', models.CharField(help_text='🇮🇳 🇺🇳 🇺🇸 etc', max_length=10)),
                ('description', models.TextField()),
                ('why_hidden', models.TextField(help_text='Why 90% students miss this')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('url', models.URLField()),
                ('has_certificate', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=True)),
                ('language', models.CharField(default='English', max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon class', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('views', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gems', to='learning.gemcategory')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('month_start', models.IntegerField(help_text='Starting month')),
                ('month_end', models.IntegerField(help_text='Ending month')),
                ('order', models.IntegerField(default=0)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='learning.roadmap')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
